=== SeeSharpSoft/json-schema-object-generator/test/validations/string-variants/schema.json
{
  "$ref": "#/definitions/MyObject",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyObject": {
      "additionalProperties": false,
      "properties": {
        "simple": {
          "type": "string"
        },
        "enum": {
          "enum": [
            "ok",
            "fail",
            "abort"
          ],
          "type": "string"
        },
        "minLength": {
          "type": "string",
          "minLength": 2
        },
        "regex": {
          "type": "string",
          "pattern": "\\w@\\w\\.\\w"
        },
        "format-date-time": {
          "type": "string",
          "format": "date-time"
        },
        "format-date": {
          "type": "string",
          "format": "date"
        },
        "format-time": {
          "type": "string",
          "format": "time"
        },
        "format-regex": {
          "type": "string",
          "format": "regex"
        },
        "format-email": {
          "type": "string",
          "format": "email"
        },
        "format-hostname": {
          "type": "string",
          "format": "hostname"
        },
        "format-ipv4": {
          "type": "string",
          "format": "ipv4"
        },
        "format-ipv6": {
          "type": "string",
          "format": "ipv6"
        },
        "format-uri": {
          "type": "string",
          "format": "uri"
        },
        "format-json-pointer": {
          "type": "string",
          "format": "json-pointer"
        },
        "format-relative-json-pointer": {
          "type": "string",
          "format": "relative-json-pointer"
        }
      },
      "required": [
        "simple",
        "enum",
        "minLength",
        "regex",
        "format-date-time",
        "format-date",
        "format-time",
        "format-regex",
        "format-email",
        "format-hostname",
        "format-ipv4",
        "format-ipv6",
        "format-uri",
        "format-json-pointer",
        "format-relative-json-pointer"
      ],
      "type": "object"
    }
  }
}

=== SeeSharpSoft/json-schema-object-generator/test/validations/string-variants/object.json
{"simple":"","enum":"ok","minLength":"ww","regex":"0@m.7","format-date-time":"2021-03-17T09:34:16.736Z","format-date":"2021-03-17","format-time":"09:34:16.736Z","format-regex":"[A-Z].+","format-email":"mail@example.org","format-hostname":"localhost","format-ipv4":"127.0.0.1","format-ipv6":"::1","format-uri":"http://example.org/","format-json-pointer":"/foo/bar","format-relative-json-pointer":"0/foo/bar"}
